### PR TITLE
Code changes to enable cross platform support

### PR DESCRIPTION
**Pull request by aquilarubra**
The proposed changes make the code more cross-platform. I used those changes to enable Windows compilation. There is still work to do, but my changes concern just ifdefs and exp10 (changed with pow), which will be needed anyway. Some additional files allow to fix paths in mingw and do not affect Linux compilation. I also added a couple of cross-platform libraries to substitute some posix ones in mingw (just the needed subset). I would prefer if those fixes are in master rather than branching, as they concern good coding standards for cross-platform applications and suppress some platform dependent code.

### CODE REVIEW

**Comment by terminator356** [comment]
Hi, my fixes to wavecanvas.cpp have slightly conflicted the request.
It appears to be just trivial header stuff at the top.
Can you tidy it up for me? Thanks.

**Comment by aquilarubra** [comment]
Thank you Tim. Now that I remember, it was the only file I borrowed from 
the Mac cross compiling branch. So, your fix works for Windows now.

I updated my branch with your fix. It is the first time I use git... so 
please be patient. I don't know if I need to do something else to tidy 
it.

**Comment by terminator356** [comment]
Reviewing... A lot of it looks OK at first glance. Nice work, must have taken a long time.
I'd like to request a rather big change:

ALSA stuff: I am not sure why it was necessary to hard-code _WIN32 lines like this:

`extern void exitJackAudio();
extern void exitDummyAudio();
extern void exitOSC();
#ifndef _WIN32
extern void exitMidiAlsa();
#endif`

It should not have been necessary to change anything in regards to ALSA,
 especially wholesale hard-coded exclusions.
Except perhaps in the main cmake file where we might purposely exclude ALSA
 from even being an option at all if say, Windows is the platform.
After that, if ALSA support is not enabled, the code takes care of itself and nothing
 further _should_ be required.
But I am aware of a few remaining visual items of concern. For example:
The "Add ALSA" push-button in the midi configuration dialog.
That's my fault, I never got around to hiding the button if ALSA support isn't compiled in.

Yes, specific small areas of concern like that can be wrapped in #ifdef's but 
 in those cases you should probably use
 `#ifdef ALSA_SUPPORT` instead of hard-coding `#ifdef _WIN32`.
Consider BSD, which does not support ALSA. Thus, to be at least... consistent,
 you'd have to start including all OS's that don't have ALSA like this:
`#ifdef _WIN32 || #ifdef _BSD || #ifdef _<OTHER OS>`
(Probably wrong syntax but should be clear.)
Also consider that some day, ALSA might (a big might) be ported to Windows. What then?
So in my view the ALSA skeleton stuff that's already there should remain there,
 and all ALSA support code should be turned on or off from the main cmake file
 via the ALSA_SUPPORT def.

As I say if there's any specific remaining problems or mention of the word "ALSA"
 we can deal with it as we go.
I trust MusE should at least compile fine as-is simply with cmake ALSA support turned off.
Did it not? We can fix those specific places.

Also I'd like to talk about the exp10() stuff but I'll await your response.
Thanks!

**Comment by terminator356** [comment]
Oh! I think I see what happened. If some of the code was borrowed from 
 spamatica's branch, I think that branch was made **before** I added the ability
 to make ALSA support an option ! So spamatica may have had no choice but
 to hard-code it like that, at the time.
 Well, I've stated what I think needs to be done moving forward with this...

**Comment by aquilarubra** [comment]
Ok, I got the point. I'll check that. Indeed, it was not enough to disable alsa in the cmake file. I could also only make MusE compile statically, otherwise it could not resolve extern functions. That will have to be figured out next.

Concerning exp10, there was a single file where I left it, as there was a definition. Maybe, it could be placed somewhere globally and leave exp10 everywhere. Strangely, mingw64 libraries do not provide it.

On February 17, 2019 12:01:54 AM GMT+01:00, Tim <notifications@github.com> wrote:
>Reviewing... A lot of it looks OK at first glance. Nice work, must have
>taken a long time.
>I'd like to request a rather big change:
>
>ALSA stuff: I am not sure why it was necessary to hard-code _WIN32
>lines like this:
>
>`extern void exitJackAudio();
>extern void exitDummyAudio();
>extern void exitOSC();
>#ifndef _WIN32
>extern void exitMidiAlsa();
>#endif`
>
>It should not have been necessary to change anything in regards to
>ALSA,
> especially wholesale hard-coded exclusions.
>Except perhaps in the main cmake file where we might purposely exclude
>ALSA
> from even being an option at all if say, Windows is the platform.
>After that, if ALSA support is not enabled, the code takes care of
>itself and nothing
> further _should_ be required.
>But I am aware of a few remaining visual items of concern. For example:
>The "Add ALSA" push-button in the midi configuration dialog.
>That's my fault, I never got around to hiding the button if ALSA
>support isn't compiled in.
>
>Yes, specific small areas of concern like that can be wrapped in
>#ifdef's but 
> in those cases you should probably use
> `#ifdef ALSA_SUPPORT` instead of hard-coding `#ifdef _WIN32`.
>Consider BSD, which does not support ALSA. Thus, to be at least...
>consistent,
> you'd have to start including all OS's that don't have ALSA like this:
>`#ifdef _WIN32 || #ifdef _BSD || #ifdef _<OTHER OS>`
>(Probably wrong syntax but should be clear.)
>Also consider that some day, ALSA might (a big might) be ported to
>Windows. What then?
>So in my view the ALSA skeleton stuff that's already there should
>remain there,
>and all ALSA support code should be turned on or off from the main
>cmake file
> via the ALSA_SUPPORT def.
>
>As I say if there's any specific remaining problems or mention of the
>word "ALSA"
> we can deal with it as we go.
>I trust MusE should at least compile fine as-is simply with cmake ALSA
>support turned off.
>Did it not? We can fix those specific places.
>
>Also I'd like to talk about the exp10() stuff but I'll await your
>response.
>Thanks!
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/muse-sequencer/muse/pull/641#issuecomment-464397150

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by terminator356** [comment]
I just pushed some changes to master that should have been done long ago.
`
 - Fix all uses of exp10().
   exp10 is now detected in the main cmake file, and defined as pow(10,x) in muse_math.h
    if it is NOT found. All relevant places using exp10 now have the muse_math.h
    header instead of <cmath> or "math.h".
 - Fix compile breakage if DSSI support not enabled.
   Oops, fixed scanDssiPlugins() in plugin_cache_writer.cpp and oops, removed
    duplicate "void initDSSI() {}" from alsamidi.cpp (how'd that get there?)
`
You're probably gonna hate me for this, but I had to keep all 32 of the exp10 usages.
That means you'll have to somehow pull my changes, or remove all 32 of
  the exp10 > pow(10,x) changes that were made. Or let me do it (see below).
Sorry I had to this in order to pull these master fixes into a local copy of your branch.
I am modifying your branch. It would NOT compile out-of-box here on Linux.
I found some mistakes. I will do the exp10 stuff and I will try to do the ALSA stuff as well.
Hang in there... and don't sweat it, you don't have to go too nuts adding any big changes
 to your branch yet, I'm almost done here. We'll work through this.
After this, one of two things might happen:
1) You'll get a .diff file from me to be applied to
 your branch (sigh, I cannot seem to push my local copy of your branch to OUR repo!
 probably a naming thing, I see it's also named 'master', maybe it should have been
 branched from ours and named at the same time),
2) Your work will be merged. Let's see how this goes, OK?
Later...
Cheers.

**Comment by aquilarubra** [comment]
Ups, I also worked in the meantime, fixed all the alsa related points, and I also changed all #ifdef _WIN32 to #if defined(_WIN64) || defined(_WIN32), as I saw this in other parts of the code.

At this point I should not update my branch then and wait. In the meantime I will study how to deal with differences in git.

On February 17, 2019 8:51:26 AM GMT+01:00, Tim <notifications@github.com> wrote:
>I just pushed some changes to master that should have been done long
>ago.
>`
> - Fix all uses of exp10().
>exp10 is now detected in the main cmake file, and defined as pow(10,x)
>in muse_math.h
>if it is NOT found. All relevant places using exp10 now have the
>muse_math.h
>    header instead of <cmath> or "math.h".
> - Fix compile breakage if DSSI support not enabled.
>Oops, fixed scanDssiPlugins() in plugin_cache_writer.cpp and oops,
>removed
>duplicate "void initDSSI() {}" from alsamidi.cpp (how'd that get
>there?)
>`
>You're probably gonna hate me for this, but I had to keep all 32 of the
>exp10 usages.
>That means you'll have to somehow pull my changes, or remove all 32 of
>the exp10 > pow(10,x) changes that were made. Or let me do it (see
>below).
>Sorry I had to this in order to pull these master fixes into a local
>copy of your branch.
>I am modifying your branch. It would NOT compile out-of-box here on
>Linux.
>I found some mistakes. I will do the exp10 stuff and I will try to do
>the ALSA stuff as well.
>Hang in there... and don't sweat it, you don't have to go too nuts
>adding any big changes
> to your branch yet, I'm almost done here. We'll work through this.
>After this, one of two things might happen:
>1) You'll get a .diff file from me to be applied to
>your branch (sigh, I cannot seem to push my local copy of your branch
>to OUR repo!
>probably a naming thing, I see it's also named 'master', maybe it
>should have been
> branched from ours and named at the same time),
>2) Your work will be merged. Let's see how this goes, OK?
>Later...
>Cheers.
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/muse-sequencer/muse/pull/641#issuecomment-464426310

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
