### PR TITLE
Added File->New from template

### PR DESCRIPTION
**Pull request by kybos**
As discussed in #713.

I get the message "Can’t automatically merge. Don’t worry, you can still create the pull request. ". 
Is that a problem? Should I merge/rebase with current master first?

### CODE REVIEW

**Comment by kybos** [comment]
OK, it's only the change log, should be easy to resolve.
I am not able to do it, no write access to repo.

**Comment by terminator356** [comment]
Fixed. Thanks.

**Comment by kybos** [comment]
Thanks.
Not sure if "New from template" action should be added to the toolbar as well?

**Comment by terminator356** [comment]
Sounds good. Go for it!
(FYI If ever you need to create a new toolbar, heed the NOTICEs in there about toolbar names.)

**Pull request merged**
