### PR TITLE
Translation fixes

### PR DESCRIPTION
**Pull request by kybos**
Fixes for translation, as discussed in #729

### CODE REVIEW

**Comment by terminator356** [comment]
Thanks for the great help on the translation stuff.
Hey, I mentioned I neglected to add 'components' to share/locale/CMakeLists.txt
Can you add it and see what happens? And any other folders that should be there?
I'm in another branch ATM...

**Comment by kybos** [comment]
OK, will try that out tomorrow...
So there are still more texts coming ;-).

**Comment by kybos** [comment]
> Hey, I mentioned I neglected to add 'components' to share/locale/CMakeLists.txt
> Can you add it and see what happens? And any other folders that should be there?

I added "components" and updated but there is no difference in the number of source texts.

**Comment by terminator356** [comment]
Hm, funny I could swear there's a bunch 'o translatable text in those components. Maybe not?

**Comment by kybos** [comment]
Yes there is, but I have the impression these texts were already there before.

**Comment by terminator356** [comment]
I might have broken any links by moving many files from the widget folder
 to the components folder

**Pull request merged**
