### PR TITLE
Added script for MIDI timestretch and fixed small bug when receiving results

### PR DESCRIPTION
**Pull request by StaffanMelin**
Hi! Trying to get into MusE development, so I started with adding the requested script.

There was a bug in scripts.cpp, so when reading back the modified MIDI data from the script, all CONTROLLER events were misinitialized (tick was not read and set). I have fixed this too.

Re: https://github.com/muse-sequencer/muse/issues/1037

### CODE REVIEW

**Comment by spamatica** [comment]
I didn't try running the script but it looks good. Good catch on the bug!
One last thing before merging, please add a line in the ChangeLog file along the same lines as the previous entries.

**Comment by spamatica** [comment]
Regarding the related ticket. 
It is good to mention the ticket number (in this case #1037) in the related commit message, this way github will automatically reference the commit in the ticket.

**Comment by StaffanMelin** [comment]
Sorry, somehow I messed up (still new to Git). Was trying to do another pull request fixing issue #1022, but somehow this got merged into the first pull request. So the changes in pianoroll.cpp are for the second fix (ie #1022).

Will this still be ok or do I have to redo it somehow?

**Comment by spamatica** [comment]
Hey hey, sorry, missed the continuation of this. 
I see the other fix still there, looks trivial though so I'll go ahead and merge

**Pull request merged**
